ignore:
  - "core-customize/hybris/bin/custom/cxdevtools/**/backoffice/src/**/*"
  - "core-customize/hybris/bin/custom/cxdevtools/**/gensrc/**/*"
  - "core-customize/hybris/bin/custom/cxdevtools/**/testsrc/**/*"
